// WYZ API - Generic Statement Analyzer
// Strict account-table version:
// - For bank account statements, Balance is NEVER used as transaction amount.
// - Account rows are accepted only when the final 3 numeric columns are:
//   Debit Amount | Credit Amount | Balance.
// - Debit > 0 => DR / expenses.
// - Credit > 0 => CR / income unless ignored by transfer rules.
// - Description and Ref/Cheque No are split where possible.
// - No LLM is used for extraction.

const MODEL = 'claude-haiku-4-5-20251001';
const INSIGHT_MAX_TOKENS = 450;
const INSIGHT_TIMEOUT_MS = 18000;
const MAX_TOTAL_CHARS = 900000;
const REJECT_ABOVE_CHARS = 1400000;

const NUM_SRC = String.raw`-?\(?\d{1,3}(?:,\d{3})*(?:\.\d+)?\)?|-?\(?\d+(?:\.\d+)?\)?|\.\d+`;

function setCors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

function normalizeSpaces(s) {
  return String(s || '')
    .replace(/[\u200B-\u200D\uFEFF]/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFC/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/\uFFFE/g, '')
    .replace(/\uFFFD/g, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/\s+([,.:;])/g, '$1')
    .trim();
}
